// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2BQHUyNfc7nZT5tNfaL3a_gPLCeDcfms',
    appId: '1:730164915812:web:52eb0469cacbc8318a3971',
    messagingSenderId: '730164915812',
    projectId: 'dumper-a11b4',
    authDomain: 'dumper-a11b4.firebaseapp.com',
    storageBucket: 'dumper-a11b4.appspot.com',
    measurementId: 'G-VM3F6DDRNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz6kvKAsMO9FXWVeSVgm13Y9DQlw3fJwo',
    appId: '1:730164915812:android:37f67facb07e69a08a3971',
    messagingSenderId: '730164915812',
    projectId: 'dumper-a11b4',
    storageBucket: 'dumper-a11b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2Ul0ijKLHlji64P9nDvDBfWT9Sq40pE',
    appId: '1:730164915812:ios:98e6a8394331b3a08a3971',
    messagingSenderId: '730164915812',
    projectId: 'dumper-a11b4',
    storageBucket: 'dumper-a11b4.appspot.com',
    iosClientId: '730164915812-ef9lhbrk7ca9mn9hll4clkcnp5dueg18.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
